/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErrorOrMultipleErrorsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorOrMultipleErrorsResponse{}

// ErrorOrMultipleErrorsResponse struct for ErrorOrMultipleErrorsResponse
type ErrorOrMultipleErrorsResponse struct {
	Status string `json:"status"`
	// Single error message (when only one error occurred)
	Error *string `json:"error,omitempty"`
	// Array of error messages (when multiple validation errors occurred)
	Errors []string `json:"errors,omitempty"`
}

type _ErrorOrMultipleErrorsResponse ErrorOrMultipleErrorsResponse

// NewErrorOrMultipleErrorsResponse instantiates a new ErrorOrMultipleErrorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorOrMultipleErrorsResponse(status string) *ErrorOrMultipleErrorsResponse {
	this := ErrorOrMultipleErrorsResponse{}
	this.Status = status
	return &this
}

// NewErrorOrMultipleErrorsResponseWithDefaults instantiates a new ErrorOrMultipleErrorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorOrMultipleErrorsResponseWithDefaults() *ErrorOrMultipleErrorsResponse {
	this := ErrorOrMultipleErrorsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *ErrorOrMultipleErrorsResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ErrorOrMultipleErrorsResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ErrorOrMultipleErrorsResponse) SetStatus(v string) {
	o.Status = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ErrorOrMultipleErrorsResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorOrMultipleErrorsResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ErrorOrMultipleErrorsResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ErrorOrMultipleErrorsResponse) SetError(v string) {
	o.Error = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ErrorOrMultipleErrorsResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorOrMultipleErrorsResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ErrorOrMultipleErrorsResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *ErrorOrMultipleErrorsResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o ErrorOrMultipleErrorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorOrMultipleErrorsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *ErrorOrMultipleErrorsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorOrMultipleErrorsResponse := _ErrorOrMultipleErrorsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorOrMultipleErrorsResponse)

	if err != nil {
		return err
	}

	*o = ErrorOrMultipleErrorsResponse(varErrorOrMultipleErrorsResponse)

	return err
}

type NullableErrorOrMultipleErrorsResponse struct {
	value *ErrorOrMultipleErrorsResponse
	isSet bool
}

func (v NullableErrorOrMultipleErrorsResponse) Get() *ErrorOrMultipleErrorsResponse {
	return v.value
}

func (v *NullableErrorOrMultipleErrorsResponse) Set(val *ErrorOrMultipleErrorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorOrMultipleErrorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorOrMultipleErrorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorOrMultipleErrorsResponse(val *ErrorOrMultipleErrorsResponse) *NullableErrorOrMultipleErrorsResponse {
	return &NullableErrorOrMultipleErrorsResponse{value: val, isSet: true}
}

func (v NullableErrorOrMultipleErrorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorOrMultipleErrorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


