/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type SubmissionData struct {
	Css string `json:"css,omitempty"`
	Data map[string]interface{} `json:"data"`
	DataRequests []CreateSubmissionDataRequestData `json:"data_requests,omitempty"`
	FieldOverrides map[string]interface{} `json:"field_overrides,omitempty"`
	Html string `json:"html,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Password string `json:"password,omitempty"`
	Test bool `json:"test,omitempty"`
}
