/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type CombinedSubmissionData struct {
	ExpiresIn int32 `json:"expires_in,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	SubmissionIds []string `json:"submission_ids"`
	Test bool `json:"test,omitempty"`
}
