/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateDeleteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateDeleteResponse{}

// TemplateDeleteResponse struct for TemplateDeleteResponse
type TemplateDeleteResponse struct {
	Status string `json:"status"`
	Errors []string `json:"errors,omitempty"`
	LatestVersion NullableString `json:"latest_version,omitempty"`
	Versions []map[string]interface{} `json:"versions,omitempty"`
}

type _TemplateDeleteResponse TemplateDeleteResponse

// NewTemplateDeleteResponse instantiates a new TemplateDeleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateDeleteResponse(status string) *TemplateDeleteResponse {
	this := TemplateDeleteResponse{}
	this.Status = status
	return &this
}

// NewTemplateDeleteResponseWithDefaults instantiates a new TemplateDeleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateDeleteResponseWithDefaults() *TemplateDeleteResponse {
	this := TemplateDeleteResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *TemplateDeleteResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TemplateDeleteResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TemplateDeleteResponse) SetStatus(v string) {
	o.Status = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *TemplateDeleteResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateDeleteResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *TemplateDeleteResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *TemplateDeleteResponse) SetErrors(v []string) {
	o.Errors = v
}

// GetLatestVersion returns the LatestVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateDeleteResponse) GetLatestVersion() string {
	if o == nil || IsNil(o.LatestVersion.Get()) {
		var ret string
		return ret
	}
	return *o.LatestVersion.Get()
}

// GetLatestVersionOk returns a tuple with the LatestVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateDeleteResponse) GetLatestVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LatestVersion.Get(), o.LatestVersion.IsSet()
}

// HasLatestVersion returns a boolean if a field has been set.
func (o *TemplateDeleteResponse) HasLatestVersion() bool {
	if o != nil && o.LatestVersion.IsSet() {
		return true
	}

	return false
}

// SetLatestVersion gets a reference to the given NullableString and assigns it to the LatestVersion field.
func (o *TemplateDeleteResponse) SetLatestVersion(v string) {
	o.LatestVersion.Set(&v)
}
// SetLatestVersionNil sets the value for LatestVersion to be an explicit nil
func (o *TemplateDeleteResponse) SetLatestVersionNil() {
	o.LatestVersion.Set(nil)
}

// UnsetLatestVersion ensures that no value is present for LatestVersion, not even an explicit nil
func (o *TemplateDeleteResponse) UnsetLatestVersion() {
	o.LatestVersion.Unset()
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *TemplateDeleteResponse) GetVersions() []map[string]interface{} {
	if o == nil || IsNil(o.Versions) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateDeleteResponse) GetVersionsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *TemplateDeleteResponse) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given []map[string]interface{} and assigns it to the Versions field.
func (o *TemplateDeleteResponse) SetVersions(v []map[string]interface{}) {
	o.Versions = v
}

func (o TemplateDeleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateDeleteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if o.LatestVersion.IsSet() {
		toSerialize["latest_version"] = o.LatestVersion.Get()
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}
	return toSerialize, nil
}

func (o *TemplateDeleteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateDeleteResponse := _TemplateDeleteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateDeleteResponse)

	if err != nil {
		return err
	}

	*o = TemplateDeleteResponse(varTemplateDeleteResponse)

	return err
}

type NullableTemplateDeleteResponse struct {
	value *TemplateDeleteResponse
	isSet bool
}

func (v NullableTemplateDeleteResponse) Get() *TemplateDeleteResponse {
	return v.value
}

func (v *NullableTemplateDeleteResponse) Set(val *TemplateDeleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateDeleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateDeleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateDeleteResponse(val *TemplateDeleteResponse) *NullableTemplateDeleteResponse {
	return &NullableTemplateDeleteResponse{value: val, isSet: true}
}

func (v NullableTemplateDeleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateDeleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


