/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCombinedSubmissionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCombinedSubmissionResponse{}

// CreateCombinedSubmissionResponse struct for CreateCombinedSubmissionResponse
type CreateCombinedSubmissionResponse struct {
	Status string `json:"status"`
	CombinedSubmission CombinedSubmission `json:"combined_submission"`
	Errors []string `json:"errors,omitempty"`
}

type _CreateCombinedSubmissionResponse CreateCombinedSubmissionResponse

// NewCreateCombinedSubmissionResponse instantiates a new CreateCombinedSubmissionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCombinedSubmissionResponse(status string, combinedSubmission CombinedSubmission) *CreateCombinedSubmissionResponse {
	this := CreateCombinedSubmissionResponse{}
	this.Status = status
	this.CombinedSubmission = combinedSubmission
	return &this
}

// NewCreateCombinedSubmissionResponseWithDefaults instantiates a new CreateCombinedSubmissionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCombinedSubmissionResponseWithDefaults() *CreateCombinedSubmissionResponse {
	this := CreateCombinedSubmissionResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateCombinedSubmissionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateCombinedSubmissionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateCombinedSubmissionResponse) SetStatus(v string) {
	o.Status = v
}

// GetCombinedSubmission returns the CombinedSubmission field value
func (o *CreateCombinedSubmissionResponse) GetCombinedSubmission() CombinedSubmission {
	if o == nil {
		var ret CombinedSubmission
		return ret
	}

	return o.CombinedSubmission
}

// GetCombinedSubmissionOk returns a tuple with the CombinedSubmission field value
// and a boolean to check if the value has been set.
func (o *CreateCombinedSubmissionResponse) GetCombinedSubmissionOk() (*CombinedSubmission, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CombinedSubmission, true
}

// SetCombinedSubmission sets field value
func (o *CreateCombinedSubmissionResponse) SetCombinedSubmission(v CombinedSubmission) {
	o.CombinedSubmission = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateCombinedSubmissionResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCombinedSubmissionResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateCombinedSubmissionResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *CreateCombinedSubmissionResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o CreateCombinedSubmissionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCombinedSubmissionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["combined_submission"] = o.CombinedSubmission
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *CreateCombinedSubmissionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"combined_submission",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCombinedSubmissionResponse := _CreateCombinedSubmissionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCombinedSubmissionResponse)

	if err != nil {
		return err
	}

	*o = CreateCombinedSubmissionResponse(varCreateCombinedSubmissionResponse)

	return err
}

type NullableCreateCombinedSubmissionResponse struct {
	value *CreateCombinedSubmissionResponse
	isSet bool
}

func (v NullableCreateCombinedSubmissionResponse) Get() *CreateCombinedSubmissionResponse {
	return v.value
}

func (v *NullableCreateCombinedSubmissionResponse) Set(val *CreateCombinedSubmissionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCombinedSubmissionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCombinedSubmissionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCombinedSubmissionResponse(val *CreateCombinedSubmissionResponse) *NullableCreateCombinedSubmissionResponse {
	return &NullableCreateCombinedSubmissionResponse{value: val, isSet: true}
}

func (v NullableCreateCombinedSubmissionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCombinedSubmissionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


