/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type Template1Defaults struct {
	Color string `json:"color,omitempty"`
	FontSize float32 `json:"fontSize,omitempty"`
	Typeface string `json:"typeface,omitempty"`
}
