/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Submission422Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Submission422Response{}

// Submission422Response struct for Submission422Response
type Submission422Response struct {
	Status string `json:"status"`
	// Single error message (for non-validation errors)
	Error *string `json:"error,omitempty"`
	Submission *SubmissionPreview `json:"submission,omitempty"`
	// Array of validation error messages (when submission data is invalid)
	Errors []string `json:"errors,omitempty"`
}

type _Submission422Response Submission422Response

// NewSubmission422Response instantiates a new Submission422Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmission422Response(status string) *Submission422Response {
	this := Submission422Response{}
	this.Status = status
	return &this
}

// NewSubmission422ResponseWithDefaults instantiates a new Submission422Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmission422ResponseWithDefaults() *Submission422Response {
	this := Submission422Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *Submission422Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Submission422Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Submission422Response) SetStatus(v string) {
	o.Status = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *Submission422Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Submission422Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *Submission422Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *Submission422Response) SetError(v string) {
	o.Error = &v
}

// GetSubmission returns the Submission field value if set, zero value otherwise.
func (o *Submission422Response) GetSubmission() SubmissionPreview {
	if o == nil || IsNil(o.Submission) {
		var ret SubmissionPreview
		return ret
	}
	return *o.Submission
}

// GetSubmissionOk returns a tuple with the Submission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Submission422Response) GetSubmissionOk() (*SubmissionPreview, bool) {
	if o == nil || IsNil(o.Submission) {
		return nil, false
	}
	return o.Submission, true
}

// HasSubmission returns a boolean if a field has been set.
func (o *Submission422Response) HasSubmission() bool {
	if o != nil && !IsNil(o.Submission) {
		return true
	}

	return false
}

// SetSubmission gets a reference to the given SubmissionPreview and assigns it to the Submission field.
func (o *Submission422Response) SetSubmission(v SubmissionPreview) {
	o.Submission = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Submission422Response) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Submission422Response) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Submission422Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *Submission422Response) SetErrors(v []string) {
	o.Errors = v
}

func (o Submission422Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Submission422Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Submission) {
		toSerialize["submission"] = o.Submission
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *Submission422Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmission422Response := _Submission422Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmission422Response)

	if err != nil {
		return err
	}

	*o = Submission422Response(varSubmission422Response)

	return err
}

type NullableSubmission422Response struct {
	value *Submission422Response
	isSet bool
}

func (v NullableSubmission422Response) Get() *Submission422Response {
	return v.value
}

func (v *NullableSubmission422Response) Set(val *Submission422Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmission422Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmission422Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmission422Response(val *Submission422Response) *NullableSubmission422Response {
	return &NullableSubmission422Response{value: val, isSet: true}
}

func (v NullableSubmission422Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmission422Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


