/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type SubmissionBatch struct {
	PendingCount int32 `json:"pending_count,omitempty"`
	CompletionPercentage int32 `json:"completion_percentage,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	TotalCount int32 `json:"total_count,omitempty"`
	Submissions []Submission `json:"submissions,omitempty"`
	ProcessedAt string `json:"processed_at,omitempty"`
	Id string `json:"id,omitempty"`
	State string `json:"state,omitempty"`
	ErrorCount int32 `json:"error_count,omitempty"`
}
