/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type UploadTemplateDataDocument struct {
	Metadata UploadTemplateDataDocumentMetadata `json:"metadata,omitempty"`
	Id string `json:"id,omitempty"`
	Storage string `json:"storage,omitempty"`
}
