/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSubmissionDataRequestTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionDataRequestTokenResponse{}

// CreateSubmissionDataRequestTokenResponse struct for CreateSubmissionDataRequestTokenResponse
type CreateSubmissionDataRequestTokenResponse struct {
	Status string `json:"status"`
	Token SubmissionDataRequestToken `json:"token"`
	Errors []string `json:"errors,omitempty"`
}

type _CreateSubmissionDataRequestTokenResponse CreateSubmissionDataRequestTokenResponse

// NewCreateSubmissionDataRequestTokenResponse instantiates a new CreateSubmissionDataRequestTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionDataRequestTokenResponse(status string, token SubmissionDataRequestToken) *CreateSubmissionDataRequestTokenResponse {
	this := CreateSubmissionDataRequestTokenResponse{}
	this.Status = status
	this.Token = token
	return &this
}

// NewCreateSubmissionDataRequestTokenResponseWithDefaults instantiates a new CreateSubmissionDataRequestTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionDataRequestTokenResponseWithDefaults() *CreateSubmissionDataRequestTokenResponse {
	this := CreateSubmissionDataRequestTokenResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateSubmissionDataRequestTokenResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionDataRequestTokenResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateSubmissionDataRequestTokenResponse) SetStatus(v string) {
	o.Status = v
}

// GetToken returns the Token field value
func (o *CreateSubmissionDataRequestTokenResponse) GetToken() SubmissionDataRequestToken {
	if o == nil {
		var ret SubmissionDataRequestToken
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionDataRequestTokenResponse) GetTokenOk() (*SubmissionDataRequestToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *CreateSubmissionDataRequestTokenResponse) SetToken(v SubmissionDataRequestToken) {
	o.Token = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateSubmissionDataRequestTokenResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionDataRequestTokenResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateSubmissionDataRequestTokenResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *CreateSubmissionDataRequestTokenResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o CreateSubmissionDataRequestTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionDataRequestTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["token"] = o.Token
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *CreateSubmissionDataRequestTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubmissionDataRequestTokenResponse := _CreateSubmissionDataRequestTokenResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSubmissionDataRequestTokenResponse)

	if err != nil {
		return err
	}

	*o = CreateSubmissionDataRequestTokenResponse(varCreateSubmissionDataRequestTokenResponse)

	return err
}

type NullableCreateSubmissionDataRequestTokenResponse struct {
	value *CreateSubmissionDataRequestTokenResponse
	isSet bool
}

func (v NullableCreateSubmissionDataRequestTokenResponse) Get() *CreateSubmissionDataRequestTokenResponse {
	return v.value
}

func (v *NullableCreateSubmissionDataRequestTokenResponse) Set(val *CreateSubmissionDataRequestTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionDataRequestTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionDataRequestTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionDataRequestTokenResponse(val *CreateSubmissionDataRequestTokenResponse) *NullableCreateSubmissionDataRequestTokenResponse {
	return &NullableCreateSubmissionDataRequestTokenResponse{value: val, isSet: true}
}

func (v NullableCreateSubmissionDataRequestTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionDataRequestTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


