/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type InvalidRequest struct {
	Status string `json:"status"`
	Errors []string `json:"errors"`
}
