/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubmissionPreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmissionPreview{}

// SubmissionPreview struct for SubmissionPreview
type SubmissionPreview struct {
	BatchId NullableString `json:"batch_id"`
	DataRequests []SubmissionDataRequest `json:"data_requests"`
	Editable NullableBool `json:"editable"`
	Expired bool `json:"expired"`
	ExpiresAt NullableString `json:"expires_at"`
	Id NullableString `json:"id"`
	JsonSchemaErrors []string `json:"json_schema_errors"`
	Metadata map[string]interface{} `json:"metadata"`
	Password NullableString `json:"password"`
	ProcessedAt NullableString `json:"processed_at"`
	State string `json:"state"`
	TemplateId NullableString `json:"template_id"`
	TemplateType string `json:"template_type"`
	TemplateVersion NullableString `json:"template_version"`
	Test bool `json:"test"`
	TruncatedText map[string]interface{} `json:"truncated_text"`
	PdfHash NullableString `json:"pdf_hash"`
	DownloadUrl NullableString `json:"download_url"`
	PermanentDownloadUrl NullableString `json:"permanent_download_url"`
	PreviewDownloadUrl NullableString `json:"preview_download_url"`
	PreviewGeneratedAt NullableString `json:"preview_generated_at"`
	AuditTrailDownloadUrl NullableString `json:"audit_trail_download_url"`
	Actions []SubmissionAction `json:"actions"`
}

type _SubmissionPreview SubmissionPreview

// NewSubmissionPreview instantiates a new SubmissionPreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmissionPreview(batchId NullableString, dataRequests []SubmissionDataRequest, editable NullableBool, expired bool, expiresAt NullableString, id NullableString, jsonSchemaErrors []string, metadata map[string]interface{}, password NullableString, processedAt NullableString, state string, templateId NullableString, templateType string, templateVersion NullableString, test bool, truncatedText map[string]interface{}, pdfHash NullableString, downloadUrl NullableString, permanentDownloadUrl NullableString, previewDownloadUrl NullableString, previewGeneratedAt NullableString, auditTrailDownloadUrl NullableString, actions []SubmissionAction) *SubmissionPreview {
	this := SubmissionPreview{}
	this.BatchId = batchId
	this.DataRequests = dataRequests
	this.Editable = editable
	this.Expired = expired
	this.ExpiresAt = expiresAt
	this.Id = id
	this.JsonSchemaErrors = jsonSchemaErrors
	this.Metadata = metadata
	this.Password = password
	this.ProcessedAt = processedAt
	this.State = state
	this.TemplateId = templateId
	this.TemplateType = templateType
	this.TemplateVersion = templateVersion
	this.Test = test
	this.TruncatedText = truncatedText
	this.PdfHash = pdfHash
	this.DownloadUrl = downloadUrl
	this.PermanentDownloadUrl = permanentDownloadUrl
	this.PreviewDownloadUrl = previewDownloadUrl
	this.PreviewGeneratedAt = previewGeneratedAt
	this.AuditTrailDownloadUrl = auditTrailDownloadUrl
	this.Actions = actions
	return &this
}

// NewSubmissionPreviewWithDefaults instantiates a new SubmissionPreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmissionPreviewWithDefaults() *SubmissionPreview {
	this := SubmissionPreview{}
	return &this
}

// GetBatchId returns the BatchId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetBatchId() string {
	if o == nil || o.BatchId.Get() == nil {
		var ret string
		return ret
	}

	return *o.BatchId.Get()
}

// GetBatchIdOk returns a tuple with the BatchId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetBatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatchId.Get(), o.BatchId.IsSet()
}

// SetBatchId sets field value
func (o *SubmissionPreview) SetBatchId(v string) {
	o.BatchId.Set(&v)
}

// GetDataRequests returns the DataRequests field value
func (o *SubmissionPreview) GetDataRequests() []SubmissionDataRequest {
	if o == nil {
		var ret []SubmissionDataRequest
		return ret
	}

	return o.DataRequests
}

// GetDataRequestsOk returns a tuple with the DataRequests field value
// and a boolean to check if the value has been set.
func (o *SubmissionPreview) GetDataRequestsOk() ([]SubmissionDataRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataRequests, true
}

// SetDataRequests sets field value
func (o *SubmissionPreview) SetDataRequests(v []SubmissionDataRequest) {
	o.DataRequests = v
}

// GetEditable returns the Editable field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *SubmissionPreview) GetEditable() bool {
	if o == nil || o.Editable.Get() == nil {
		var ret bool
		return ret
	}

	return *o.Editable.Get()
}

// GetEditableOk returns a tuple with the Editable field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetEditableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Editable.Get(), o.Editable.IsSet()
}

// SetEditable sets field value
func (o *SubmissionPreview) SetEditable(v bool) {
	o.Editable.Set(&v)
}

// GetExpired returns the Expired field value
func (o *SubmissionPreview) GetExpired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value
// and a boolean to check if the value has been set.
func (o *SubmissionPreview) GetExpiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expired, true
}

// SetExpired sets field value
func (o *SubmissionPreview) SetExpired(v bool) {
	o.Expired = v
}

// GetExpiresAt returns the ExpiresAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetExpiresAt() string {
	if o == nil || o.ExpiresAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// SetExpiresAt sets field value
func (o *SubmissionPreview) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *SubmissionPreview) SetId(v string) {
	o.Id.Set(&v)
}

// GetJsonSchemaErrors returns the JsonSchemaErrors field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *SubmissionPreview) GetJsonSchemaErrors() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.JsonSchemaErrors
}

// GetJsonSchemaErrorsOk returns a tuple with the JsonSchemaErrors field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetJsonSchemaErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.JsonSchemaErrors) {
		return nil, false
	}
	return o.JsonSchemaErrors, true
}

// SetJsonSchemaErrors sets field value
func (o *SubmissionPreview) SetJsonSchemaErrors(v []string) {
	o.JsonSchemaErrors = v
}

// GetMetadata returns the Metadata field value
func (o *SubmissionPreview) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *SubmissionPreview) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *SubmissionPreview) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPassword returns the Password field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetPassword() string {
	if o == nil || o.Password.Get() == nil {
		var ret string
		return ret
	}

	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// SetPassword sets field value
func (o *SubmissionPreview) SetPassword(v string) {
	o.Password.Set(&v)
}

// GetProcessedAt returns the ProcessedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetProcessedAt() string {
	if o == nil || o.ProcessedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.ProcessedAt.Get()
}

// GetProcessedAtOk returns a tuple with the ProcessedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetProcessedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProcessedAt.Get(), o.ProcessedAt.IsSet()
}

// SetProcessedAt sets field value
func (o *SubmissionPreview) SetProcessedAt(v string) {
	o.ProcessedAt.Set(&v)
}

// GetState returns the State field value
func (o *SubmissionPreview) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *SubmissionPreview) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *SubmissionPreview) SetState(v string) {
	o.State = v
}

// GetTemplateId returns the TemplateId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetTemplateId() string {
	if o == nil || o.TemplateId.Get() == nil {
		var ret string
		return ret
	}

	return *o.TemplateId.Get()
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateId.Get(), o.TemplateId.IsSet()
}

// SetTemplateId sets field value
func (o *SubmissionPreview) SetTemplateId(v string) {
	o.TemplateId.Set(&v)
}

// GetTemplateType returns the TemplateType field value
func (o *SubmissionPreview) GetTemplateType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateType
}

// GetTemplateTypeOk returns a tuple with the TemplateType field value
// and a boolean to check if the value has been set.
func (o *SubmissionPreview) GetTemplateTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateType, true
}

// SetTemplateType sets field value
func (o *SubmissionPreview) SetTemplateType(v string) {
	o.TemplateType = v
}

// GetTemplateVersion returns the TemplateVersion field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetTemplateVersion() string {
	if o == nil || o.TemplateVersion.Get() == nil {
		var ret string
		return ret
	}

	return *o.TemplateVersion.Get()
}

// GetTemplateVersionOk returns a tuple with the TemplateVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetTemplateVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateVersion.Get(), o.TemplateVersion.IsSet()
}

// SetTemplateVersion sets field value
func (o *SubmissionPreview) SetTemplateVersion(v string) {
	o.TemplateVersion.Set(&v)
}

// GetTest returns the Test field value
func (o *SubmissionPreview) GetTest() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Test
}

// GetTestOk returns a tuple with the Test field value
// and a boolean to check if the value has been set.
func (o *SubmissionPreview) GetTestOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Test, true
}

// SetTest sets field value
func (o *SubmissionPreview) SetTest(v bool) {
	o.Test = v
}

// GetTruncatedText returns the TruncatedText field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *SubmissionPreview) GetTruncatedText() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.TruncatedText
}

// GetTruncatedTextOk returns a tuple with the TruncatedText field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetTruncatedTextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TruncatedText) {
		return map[string]interface{}{}, false
	}
	return o.TruncatedText, true
}

// SetTruncatedText sets field value
func (o *SubmissionPreview) SetTruncatedText(v map[string]interface{}) {
	o.TruncatedText = v
}

// GetPdfHash returns the PdfHash field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetPdfHash() string {
	if o == nil || o.PdfHash.Get() == nil {
		var ret string
		return ret
	}

	return *o.PdfHash.Get()
}

// GetPdfHashOk returns a tuple with the PdfHash field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetPdfHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfHash.Get(), o.PdfHash.IsSet()
}

// SetPdfHash sets field value
func (o *SubmissionPreview) SetPdfHash(v string) {
	o.PdfHash.Set(&v)
}

// GetDownloadUrl returns the DownloadUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetDownloadUrl() string {
	if o == nil || o.DownloadUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.DownloadUrl.Get()
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DownloadUrl.Get(), o.DownloadUrl.IsSet()
}

// SetDownloadUrl sets field value
func (o *SubmissionPreview) SetDownloadUrl(v string) {
	o.DownloadUrl.Set(&v)
}

// GetPermanentDownloadUrl returns the PermanentDownloadUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetPermanentDownloadUrl() string {
	if o == nil || o.PermanentDownloadUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.PermanentDownloadUrl.Get()
}

// GetPermanentDownloadUrlOk returns a tuple with the PermanentDownloadUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetPermanentDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PermanentDownloadUrl.Get(), o.PermanentDownloadUrl.IsSet()
}

// SetPermanentDownloadUrl sets field value
func (o *SubmissionPreview) SetPermanentDownloadUrl(v string) {
	o.PermanentDownloadUrl.Set(&v)
}

// GetPreviewDownloadUrl returns the PreviewDownloadUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetPreviewDownloadUrl() string {
	if o == nil || o.PreviewDownloadUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.PreviewDownloadUrl.Get()
}

// GetPreviewDownloadUrlOk returns a tuple with the PreviewDownloadUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetPreviewDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviewDownloadUrl.Get(), o.PreviewDownloadUrl.IsSet()
}

// SetPreviewDownloadUrl sets field value
func (o *SubmissionPreview) SetPreviewDownloadUrl(v string) {
	o.PreviewDownloadUrl.Set(&v)
}

// GetPreviewGeneratedAt returns the PreviewGeneratedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetPreviewGeneratedAt() string {
	if o == nil || o.PreviewGeneratedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.PreviewGeneratedAt.Get()
}

// GetPreviewGeneratedAtOk returns a tuple with the PreviewGeneratedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetPreviewGeneratedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviewGeneratedAt.Get(), o.PreviewGeneratedAt.IsSet()
}

// SetPreviewGeneratedAt sets field value
func (o *SubmissionPreview) SetPreviewGeneratedAt(v string) {
	o.PreviewGeneratedAt.Set(&v)
}

// GetAuditTrailDownloadUrl returns the AuditTrailDownloadUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubmissionPreview) GetAuditTrailDownloadUrl() string {
	if o == nil || o.AuditTrailDownloadUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.AuditTrailDownloadUrl.Get()
}

// GetAuditTrailDownloadUrlOk returns a tuple with the AuditTrailDownloadUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionPreview) GetAuditTrailDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuditTrailDownloadUrl.Get(), o.AuditTrailDownloadUrl.IsSet()
}

// SetAuditTrailDownloadUrl sets field value
func (o *SubmissionPreview) SetAuditTrailDownloadUrl(v string) {
	o.AuditTrailDownloadUrl.Set(&v)
}

// GetActions returns the Actions field value
func (o *SubmissionPreview) GetActions() []SubmissionAction {
	if o == nil {
		var ret []SubmissionAction
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *SubmissionPreview) GetActionsOk() ([]SubmissionAction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *SubmissionPreview) SetActions(v []SubmissionAction) {
	o.Actions = v
}

func (o SubmissionPreview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmissionPreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["batch_id"] = o.BatchId.Get()
	toSerialize["data_requests"] = o.DataRequests
	toSerialize["editable"] = o.Editable.Get()
	toSerialize["expired"] = o.Expired
	toSerialize["expires_at"] = o.ExpiresAt.Get()
	toSerialize["id"] = o.Id.Get()
	if o.JsonSchemaErrors != nil {
		toSerialize["json_schema_errors"] = o.JsonSchemaErrors
	}
	toSerialize["metadata"] = o.Metadata
	toSerialize["password"] = o.Password.Get()
	toSerialize["processed_at"] = o.ProcessedAt.Get()
	toSerialize["state"] = o.State
	toSerialize["template_id"] = o.TemplateId.Get()
	toSerialize["template_type"] = o.TemplateType
	toSerialize["template_version"] = o.TemplateVersion.Get()
	toSerialize["test"] = o.Test
	if o.TruncatedText != nil {
		toSerialize["truncated_text"] = o.TruncatedText
	}
	toSerialize["pdf_hash"] = o.PdfHash.Get()
	toSerialize["download_url"] = o.DownloadUrl.Get()
	toSerialize["permanent_download_url"] = o.PermanentDownloadUrl.Get()
	toSerialize["preview_download_url"] = o.PreviewDownloadUrl.Get()
	toSerialize["preview_generated_at"] = o.PreviewGeneratedAt.Get()
	toSerialize["audit_trail_download_url"] = o.AuditTrailDownloadUrl.Get()
	toSerialize["actions"] = o.Actions
	return toSerialize, nil
}

func (o *SubmissionPreview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"batch_id",
		"data_requests",
		"editable",
		"expired",
		"expires_at",
		"id",
		"json_schema_errors",
		"metadata",
		"password",
		"processed_at",
		"state",
		"template_id",
		"template_type",
		"template_version",
		"test",
		"truncated_text",
		"pdf_hash",
		"download_url",
		"permanent_download_url",
		"preview_download_url",
		"preview_generated_at",
		"audit_trail_download_url",
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmissionPreview := _SubmissionPreview{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmissionPreview)

	if err != nil {
		return err
	}

	*o = SubmissionPreview(varSubmissionPreview)

	return err
}

type NullableSubmissionPreview struct {
	value *SubmissionPreview
	isSet bool
}

func (v NullableSubmissionPreview) Get() *SubmissionPreview {
	return v.value
}

func (v *NullableSubmissionPreview) Set(val *SubmissionPreview) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmissionPreview) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmissionPreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmissionPreview(val *SubmissionPreview) *NullableSubmissionPreview {
	return &NullableSubmissionPreview{value: val, isSet: true}
}

func (v NullableSubmissionPreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmissionPreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


