/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddFieldsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddFieldsData{}

// AddFieldsData struct for AddFieldsData
type AddFieldsData struct {
	Fields []map[string]interface{} `json:"fields"`
}

type _AddFieldsData AddFieldsData

// NewAddFieldsData instantiates a new AddFieldsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddFieldsData(fields []map[string]interface{}) *AddFieldsData {
	this := AddFieldsData{}
	this.Fields = fields
	return &this
}

// NewAddFieldsDataWithDefaults instantiates a new AddFieldsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddFieldsDataWithDefaults() *AddFieldsData {
	this := AddFieldsData{}
	return &this
}

// GetFields returns the Fields field value
func (o *AddFieldsData) GetFields() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *AddFieldsData) GetFieldsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *AddFieldsData) SetFields(v []map[string]interface{}) {
	o.Fields = v
}

func (o AddFieldsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddFieldsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

func (o *AddFieldsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddFieldsData := _AddFieldsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddFieldsData)

	if err != nil {
		return err
	}

	*o = AddFieldsData(varAddFieldsData)

	return err
}

type NullableAddFieldsData struct {
	value *AddFieldsData
	isSet bool
}

func (v NullableAddFieldsData) Get() *AddFieldsData {
	return v.value
}

func (v *NullableAddFieldsData) Set(val *AddFieldsData) {
	v.value = val
	v.isSet = true
}

func (v NullableAddFieldsData) IsSet() bool {
	return v.isSet
}

func (v *NullableAddFieldsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddFieldsData(val *AddFieldsData) *NullableAddFieldsData {
	return &NullableAddFieldsData{value: val, isSet: true}
}

func (v NullableAddFieldsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddFieldsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


