/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessErrorResponse{}

// SuccessErrorResponse struct for SuccessErrorResponse
type SuccessErrorResponse struct {
	Status string `json:"status"`
	Error *string `json:"error,omitempty"`
}

type _SuccessErrorResponse SuccessErrorResponse

// NewSuccessErrorResponse instantiates a new SuccessErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessErrorResponse(status string) *SuccessErrorResponse {
	this := SuccessErrorResponse{}
	this.Status = status
	return &this
}

// NewSuccessErrorResponseWithDefaults instantiates a new SuccessErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessErrorResponseWithDefaults() *SuccessErrorResponse {
	this := SuccessErrorResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *SuccessErrorResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SuccessErrorResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SuccessErrorResponse) SetStatus(v string) {
	o.Status = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SuccessErrorResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SuccessErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *SuccessErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o SuccessErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *SuccessErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessErrorResponse := _SuccessErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessErrorResponse)

	if err != nil {
		return err
	}

	*o = SuccessErrorResponse(varSuccessErrorResponse)

	return err
}

type NullableSuccessErrorResponse struct {
	value *SuccessErrorResponse
	isSet bool
}

func (v NullableSuccessErrorResponse) Get() *SuccessErrorResponse {
	return v.value
}

func (v *NullableSuccessErrorResponse) Set(val *SuccessErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessErrorResponse(val *SuccessErrorResponse) *NullableSuccessErrorResponse {
	return &NullableSuccessErrorResponse{value: val, isSet: true}
}

func (v NullableSuccessErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


