/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSubmissionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionResponse{}

// CreateSubmissionResponse struct for CreateSubmissionResponse
type CreateSubmissionResponse struct {
	Status string `json:"status"`
	Submission SubmissionPreview `json:"submission"`
	Errors []string `json:"errors,omitempty"`
}

type _CreateSubmissionResponse CreateSubmissionResponse

// NewCreateSubmissionResponse instantiates a new CreateSubmissionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionResponse(status string, submission SubmissionPreview) *CreateSubmissionResponse {
	this := CreateSubmissionResponse{}
	this.Status = status
	this.Submission = submission
	return &this
}

// NewCreateSubmissionResponseWithDefaults instantiates a new CreateSubmissionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionResponseWithDefaults() *CreateSubmissionResponse {
	this := CreateSubmissionResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateSubmissionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateSubmissionResponse) SetStatus(v string) {
	o.Status = v
}

// GetSubmission returns the Submission field value
func (o *CreateSubmissionResponse) GetSubmission() SubmissionPreview {
	if o == nil {
		var ret SubmissionPreview
		return ret
	}

	return o.Submission
}

// GetSubmissionOk returns a tuple with the Submission field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionResponse) GetSubmissionOk() (*SubmissionPreview, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Submission, true
}

// SetSubmission sets field value
func (o *CreateSubmissionResponse) SetSubmission(v SubmissionPreview) {
	o.Submission = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateSubmissionResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateSubmissionResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *CreateSubmissionResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o CreateSubmissionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["submission"] = o.Submission
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *CreateSubmissionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"submission",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubmissionResponse := _CreateSubmissionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSubmissionResponse)

	if err != nil {
		return err
	}

	*o = CreateSubmissionResponse(varCreateSubmissionResponse)

	return err
}

type NullableCreateSubmissionResponse struct {
	value *CreateSubmissionResponse
	isSet bool
}

func (v NullableCreateSubmissionResponse) Get() *CreateSubmissionResponse {
	return v.value
}

func (v *NullableCreateSubmissionResponse) Set(val *CreateSubmissionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionResponse(val *CreateSubmissionResponse) *NullableCreateSubmissionResponse {
	return &NullableCreateSubmissionResponse{value: val, isSet: true}
}

func (v NullableCreateSubmissionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


