/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCustomFileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomFileData{}

// CreateCustomFileData struct for CreateCustomFileData
type CreateCustomFileData struct {
	CacheId string `json:"cache_id"`
}

type _CreateCustomFileData CreateCustomFileData

// NewCreateCustomFileData instantiates a new CreateCustomFileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomFileData(cacheId string) *CreateCustomFileData {
	this := CreateCustomFileData{}
	this.CacheId = cacheId
	return &this
}

// NewCreateCustomFileDataWithDefaults instantiates a new CreateCustomFileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomFileDataWithDefaults() *CreateCustomFileData {
	this := CreateCustomFileData{}
	return &this
}

// GetCacheId returns the CacheId field value
func (o *CreateCustomFileData) GetCacheId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CacheId
}

// GetCacheIdOk returns a tuple with the CacheId field value
// and a boolean to check if the value has been set.
func (o *CreateCustomFileData) GetCacheIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CacheId, true
}

// SetCacheId sets field value
func (o *CreateCustomFileData) SetCacheId(v string) {
	o.CacheId = v
}

func (o CreateCustomFileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomFileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cache_id"] = o.CacheId
	return toSerialize, nil
}

func (o *CreateCustomFileData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cache_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCustomFileData := _CreateCustomFileData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCustomFileData)

	if err != nil {
		return err
	}

	*o = CreateCustomFileData(varCreateCustomFileData)

	return err
}

type NullableCreateCustomFileData struct {
	value *CreateCustomFileData
	isSet bool
}

func (v NullableCreateCustomFileData) Get() *CreateCustomFileData {
	return v.value
}

func (v *NullableCreateCustomFileData) Set(val *CreateCustomFileData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomFileData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomFileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomFileData(val *CreateCustomFileData) *NullableCreateCustomFileData {
	return &NullableCreateCustomFileData{value: val, isSet: true}
}

func (v NullableCreateCustomFileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomFileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


