/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type Submission struct {
	Id string `json:"id"`
	TemplateId string `json:"template_id,omitempty"`
	Test bool `json:"test"`
	Editable bool `json:"editable,omitempty"`
	Expired bool `json:"expired"`
	ExpiresAt string `json:"expires_at,omitempty"`
	ProcessedAt string `json:"processed_at,omitempty"`
	State string `json:"state"`
	Data map[string]interface{} `json:"data,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	TruncatedText map[string]interface{} `json:"truncated_text,omitempty"`
	PdfHash string `json:"pdf_hash,omitempty"`
	DownloadUrl string `json:"download_url,omitempty"`
	PermanentDownloadUrl string `json:"permanent_download_url,omitempty"`
	BatchId string `json:"batch_id,omitempty"`
	DataRequests []SubmissionDataRequest `json:"data_requests,omitempty"`
	Actions []SubmissionAction `json:"actions,omitempty"`
	Source string `json:"source,omitempty"`
	Referrer string `json:"referrer,omitempty"`
}
