/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RenameFolderData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenameFolderData{}

// RenameFolderData struct for RenameFolderData
type RenameFolderData struct {
	Name string `json:"name"`
}

type _RenameFolderData RenameFolderData

// NewRenameFolderData instantiates a new RenameFolderData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenameFolderData(name string) *RenameFolderData {
	this := RenameFolderData{}
	this.Name = name
	return &this
}

// NewRenameFolderDataWithDefaults instantiates a new RenameFolderData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenameFolderDataWithDefaults() *RenameFolderData {
	this := RenameFolderData{}
	return &this
}

// GetName returns the Name field value
func (o *RenameFolderData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RenameFolderData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RenameFolderData) SetName(v string) {
	o.Name = v
}

func (o RenameFolderData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenameFolderData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *RenameFolderData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRenameFolderData := _RenameFolderData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRenameFolderData)

	if err != nil {
		return err
	}

	*o = RenameFolderData(varRenameFolderData)

	return err
}

type NullableRenameFolderData struct {
	value *RenameFolderData
	isSet bool
}

func (v NullableRenameFolderData) Get() *RenameFolderData {
	return v.value
}

func (v *NullableRenameFolderData) Set(val *RenameFolderData) {
	v.value = val
	v.isSet = true
}

func (v NullableRenameFolderData) IsSet() bool {
	return v.isSet
}

func (v *NullableRenameFolderData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenameFolderData(val *RenameFolderData) *NullableRenameFolderData {
	return &NullableRenameFolderData{value: val, isSet: true}
}

func (v NullableRenameFolderData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenameFolderData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


