/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type SubmissionDataBatchRequest struct {
	Css string `json:"css,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	Test bool `json:"test,omitempty"`
	Html string `json:"html,omitempty"`
	TemplateId string `json:"template_id,omitempty"`
}
