/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type FoldersFolder struct {
	ParentFolderId string `json:"parent_folder_id,omitempty"`
	Name string `json:"name,omitempty"`
}
