/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type Template1 struct {
	DocumentProcessed bool `json:"document_processed,omitempty"`
	ExpirationInterval string `json:"expiration_interval,omitempty"`
	Scss string `json:"scss,omitempty"`
	DocumentState string `json:"document_state,omitempty"`
	ExpireAfter float32 `json:"expire_after,omitempty"`
	Description string `json:"description,omitempty"`
	SlackWebhookUrl string `json:"slack_webhook_url,omitempty"`
	Demo bool `json:"demo,omitempty"`
	Path string `json:"path,omitempty"`
	HeaderHtml string `json:"header_html,omitempty"`
	PublicWebForm bool `json:"public_web_form,omitempty"`
	FieldOrder [][]float32 `json:"field_order,omitempty"`
	PermanentDocumentUrl string `json:"permanent_document_url,omitempty"`
	Html string `json:"html,omitempty"`
	TemplateType string `json:"template_type,omitempty"`
	Id string `json:"id,omitempty"`
	PageDimensions [][]float32 `json:"page_dimensions,omitempty"`
	Locked bool `json:"locked,omitempty"`
	PageCount float32 `json:"page_count,omitempty"`
	EncryptPdfs bool `json:"encrypt_pdfs,omitempty"`
	WebhookUrl string `json:"webhook_url,omitempty"`
	EmbedDomains []string `json:"embed_domains,omitempty"`
	ParentFolderId string `json:"parent_folder_id,omitempty"`
	AllowAdditionalProperties bool `json:"allow_additional_properties,omitempty"`
	EncryptPdfsPassword string `json:"encrypt_pdfs_password,omitempty"`
	PublicSubmissions bool `json:"public_submissions,omitempty"`
	SharedFieldData map[string]interface{} `json:"shared_field_data,omitempty"`
	DocumentMd5 string `json:"document_md5,omitempty"`
	FirstTemplate bool `json:"first_template,omitempty"`
	Defaults Template1Defaults `json:"defaults,omitempty"`
	EditableSubmissions bool `json:"editable_submissions,omitempty"`
	ExpireSubmissions bool `json:"expire_submissions,omitempty"`
	Name string `json:"name,omitempty"`
	FooterHtml string `json:"footer_html,omitempty"`
	DocumentParseError bool `json:"document_parse_error,omitempty"`
	Fields map[string]interface{} `json:"fields,omitempty"`
	DocumentFilename string `json:"document_filename,omitempty"`
	RedirectUrl string `json:"redirect_url,omitempty"`
	DocumentUrl string `json:"document_url,omitempty"`
}
