/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type CombinedSubmission struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Password string `json:"password,omitempty"`
	Expired bool `json:"expired,omitempty"`
	ExpiresAt string `json:"expires_at,omitempty"`
	SourcePdfs []map[string]interface{} `json:"source_pdfs,omitempty"`
	PdfHash string `json:"pdf_hash,omitempty"`
	DownloadUrl string `json:"download_url,omitempty"`
	SubmissionIds []string `json:"submission_ids,omitempty"`
	Id string `json:"id,omitempty"`
	State string `json:"state,omitempty"`
	Actions []CombinedSubmissionAction `json:"actions,omitempty"`
}
