/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSubmissionDataRequestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionDataRequestResponse{}

// CreateSubmissionDataRequestResponse struct for CreateSubmissionDataRequestResponse
type CreateSubmissionDataRequestResponse struct {
	Status string `json:"status"`
	DataRequest SubmissionDataRequestShow `json:"data_request"`
	Errors []string `json:"errors,omitempty"`
}

type _CreateSubmissionDataRequestResponse CreateSubmissionDataRequestResponse

// NewCreateSubmissionDataRequestResponse instantiates a new CreateSubmissionDataRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionDataRequestResponse(status string, dataRequest SubmissionDataRequestShow) *CreateSubmissionDataRequestResponse {
	this := CreateSubmissionDataRequestResponse{}
	this.Status = status
	this.DataRequest = dataRequest
	return &this
}

// NewCreateSubmissionDataRequestResponseWithDefaults instantiates a new CreateSubmissionDataRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionDataRequestResponseWithDefaults() *CreateSubmissionDataRequestResponse {
	this := CreateSubmissionDataRequestResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateSubmissionDataRequestResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionDataRequestResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateSubmissionDataRequestResponse) SetStatus(v string) {
	o.Status = v
}

// GetDataRequest returns the DataRequest field value
func (o *CreateSubmissionDataRequestResponse) GetDataRequest() SubmissionDataRequestShow {
	if o == nil {
		var ret SubmissionDataRequestShow
		return ret
	}

	return o.DataRequest
}

// GetDataRequestOk returns a tuple with the DataRequest field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionDataRequestResponse) GetDataRequestOk() (*SubmissionDataRequestShow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataRequest, true
}

// SetDataRequest sets field value
func (o *CreateSubmissionDataRequestResponse) SetDataRequest(v SubmissionDataRequestShow) {
	o.DataRequest = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateSubmissionDataRequestResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionDataRequestResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateSubmissionDataRequestResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *CreateSubmissionDataRequestResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o CreateSubmissionDataRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionDataRequestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data_request"] = o.DataRequest
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *CreateSubmissionDataRequestResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data_request",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubmissionDataRequestResponse := _CreateSubmissionDataRequestResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSubmissionDataRequestResponse)

	if err != nil {
		return err
	}

	*o = CreateSubmissionDataRequestResponse(varCreateSubmissionDataRequestResponse)

	return err
}

type NullableCreateSubmissionDataRequestResponse struct {
	value *CreateSubmissionDataRequestResponse
	isSet bool
}

func (v NullableCreateSubmissionDataRequestResponse) Get() *CreateSubmissionDataRequestResponse {
	return v.value
}

func (v *NullableCreateSubmissionDataRequestResponse) Set(val *CreateSubmissionDataRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionDataRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionDataRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionDataRequestResponse(val *CreateSubmissionDataRequestResponse) *NullableCreateSubmissionDataRequestResponse {
	return &NullableCreateSubmissionDataRequestResponse{value: val, isSet: true}
}

func (v NullableCreateSubmissionDataRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionDataRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


