/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplatePublishVersionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplatePublishVersionResponse{}

// TemplatePublishVersionResponse struct for TemplatePublishVersionResponse
type TemplatePublishVersionResponse struct {
	Status string `json:"status"`
	Result map[string]interface{} `json:"result"`
	Errors []string `json:"errors,omitempty"`
}

type _TemplatePublishVersionResponse TemplatePublishVersionResponse

// NewTemplatePublishVersionResponse instantiates a new TemplatePublishVersionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplatePublishVersionResponse(status string, result map[string]interface{}) *TemplatePublishVersionResponse {
	this := TemplatePublishVersionResponse{}
	this.Status = status
	this.Result = result
	return &this
}

// NewTemplatePublishVersionResponseWithDefaults instantiates a new TemplatePublishVersionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplatePublishVersionResponseWithDefaults() *TemplatePublishVersionResponse {
	this := TemplatePublishVersionResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *TemplatePublishVersionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TemplatePublishVersionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TemplatePublishVersionResponse) SetStatus(v string) {
	o.Status = v
}

// GetResult returns the Result field value
func (o *TemplatePublishVersionResponse) GetResult() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *TemplatePublishVersionResponse) GetResultOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *TemplatePublishVersionResponse) SetResult(v map[string]interface{}) {
	o.Result = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *TemplatePublishVersionResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatePublishVersionResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *TemplatePublishVersionResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *TemplatePublishVersionResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o TemplatePublishVersionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplatePublishVersionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["result"] = o.Result
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *TemplatePublishVersionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplatePublishVersionResponse := _TemplatePublishVersionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplatePublishVersionResponse)

	if err != nil {
		return err
	}

	*o = TemplatePublishVersionResponse(varTemplatePublishVersionResponse)

	return err
}

type NullableTemplatePublishVersionResponse struct {
	value *TemplatePublishVersionResponse
	isSet bool
}

func (v NullableTemplatePublishVersionResponse) Get() *TemplatePublishVersionResponse {
	return v.value
}

func (v *NullableTemplatePublishVersionResponse) Set(val *TemplatePublishVersionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplatePublishVersionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplatePublishVersionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplatePublishVersionResponse(val *TemplatePublishVersionResponse) *NullableTemplatePublishVersionResponse {
	return &NullableTemplatePublishVersionResponse{value: val, isSet: true}
}

func (v NullableTemplatePublishVersionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplatePublishVersionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


