/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultipleErrorsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultipleErrorsResponse{}

// MultipleErrorsResponse struct for MultipleErrorsResponse
type MultipleErrorsResponse struct {
	Status string `json:"status"`
	Errors []string `json:"errors"`
}

type _MultipleErrorsResponse MultipleErrorsResponse

// NewMultipleErrorsResponse instantiates a new MultipleErrorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultipleErrorsResponse(status string, errors []string) *MultipleErrorsResponse {
	this := MultipleErrorsResponse{}
	this.Status = status
	this.Errors = errors
	return &this
}

// NewMultipleErrorsResponseWithDefaults instantiates a new MultipleErrorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultipleErrorsResponseWithDefaults() *MultipleErrorsResponse {
	this := MultipleErrorsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *MultipleErrorsResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MultipleErrorsResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MultipleErrorsResponse) SetStatus(v string) {
	o.Status = v
}

// GetErrors returns the Errors field value
func (o *MultipleErrorsResponse) GetErrors() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *MultipleErrorsResponse) GetErrorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *MultipleErrorsResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o MultipleErrorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultipleErrorsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["errors"] = o.Errors
	return toSerialize, nil
}

func (o *MultipleErrorsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"errors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultipleErrorsResponse := _MultipleErrorsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultipleErrorsResponse)

	if err != nil {
		return err
	}

	*o = MultipleErrorsResponse(varMultipleErrorsResponse)

	return err
}

type NullableMultipleErrorsResponse struct {
	value *MultipleErrorsResponse
	isSet bool
}

func (v NullableMultipleErrorsResponse) Get() *MultipleErrorsResponse {
	return v.value
}

func (v *NullableMultipleErrorsResponse) Set(val *MultipleErrorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMultipleErrorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMultipleErrorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultipleErrorsResponse(val *MultipleErrorsResponse) *NullableMultipleErrorsResponse {
	return &NullableMultipleErrorsResponse{value: val, isSet: true}
}

func (v NullableMultipleErrorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultipleErrorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


