/*
DocSpring API

Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CombinePdfsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CombinePdfsData{}

// CombinePdfsData struct for CombinePdfsData
type CombinePdfsData struct {
	DeleteCustomFiles *bool `json:"delete_custom_files,omitempty"`
	ExpiresIn *int32 `json:"expires_in,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Password *string `json:"password,omitempty"`
	SourcePdfs []map[string]interface{} `json:"source_pdfs"`
	Test *bool `json:"test,omitempty"`
}

type _CombinePdfsData CombinePdfsData

// NewCombinePdfsData instantiates a new CombinePdfsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCombinePdfsData(sourcePdfs []map[string]interface{}) *CombinePdfsData {
	this := CombinePdfsData{}
	this.SourcePdfs = sourcePdfs
	return &this
}

// NewCombinePdfsDataWithDefaults instantiates a new CombinePdfsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCombinePdfsDataWithDefaults() *CombinePdfsData {
	this := CombinePdfsData{}
	return &this
}

// GetDeleteCustomFiles returns the DeleteCustomFiles field value if set, zero value otherwise.
func (o *CombinePdfsData) GetDeleteCustomFiles() bool {
	if o == nil || IsNil(o.DeleteCustomFiles) {
		var ret bool
		return ret
	}
	return *o.DeleteCustomFiles
}

// GetDeleteCustomFilesOk returns a tuple with the DeleteCustomFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CombinePdfsData) GetDeleteCustomFilesOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteCustomFiles) {
		return nil, false
	}
	return o.DeleteCustomFiles, true
}

// HasDeleteCustomFiles returns a boolean if a field has been set.
func (o *CombinePdfsData) HasDeleteCustomFiles() bool {
	if o != nil && !IsNil(o.DeleteCustomFiles) {
		return true
	}

	return false
}

// SetDeleteCustomFiles gets a reference to the given bool and assigns it to the DeleteCustomFiles field.
func (o *CombinePdfsData) SetDeleteCustomFiles(v bool) {
	o.DeleteCustomFiles = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *CombinePdfsData) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CombinePdfsData) GetExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *CombinePdfsData) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *CombinePdfsData) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CombinePdfsData) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CombinePdfsData) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CombinePdfsData) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CombinePdfsData) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CombinePdfsData) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CombinePdfsData) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CombinePdfsData) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CombinePdfsData) SetPassword(v string) {
	o.Password = &v
}

// GetSourcePdfs returns the SourcePdfs field value
func (o *CombinePdfsData) GetSourcePdfs() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.SourcePdfs
}

// GetSourcePdfsOk returns a tuple with the SourcePdfs field value
// and a boolean to check if the value has been set.
func (o *CombinePdfsData) GetSourcePdfsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourcePdfs, true
}

// SetSourcePdfs sets field value
func (o *CombinePdfsData) SetSourcePdfs(v []map[string]interface{}) {
	o.SourcePdfs = v
}

// GetTest returns the Test field value if set, zero value otherwise.
func (o *CombinePdfsData) GetTest() bool {
	if o == nil || IsNil(o.Test) {
		var ret bool
		return ret
	}
	return *o.Test
}

// GetTestOk returns a tuple with the Test field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CombinePdfsData) GetTestOk() (*bool, bool) {
	if o == nil || IsNil(o.Test) {
		return nil, false
	}
	return o.Test, true
}

// HasTest returns a boolean if a field has been set.
func (o *CombinePdfsData) HasTest() bool {
	if o != nil && !IsNil(o.Test) {
		return true
	}

	return false
}

// SetTest gets a reference to the given bool and assigns it to the Test field.
func (o *CombinePdfsData) SetTest(v bool) {
	o.Test = &v
}

func (o CombinePdfsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CombinePdfsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeleteCustomFiles) {
		toSerialize["delete_custom_files"] = o.DeleteCustomFiles
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	toSerialize["source_pdfs"] = o.SourcePdfs
	if !IsNil(o.Test) {
		toSerialize["test"] = o.Test
	}
	return toSerialize, nil
}

func (o *CombinePdfsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_pdfs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCombinePdfsData := _CombinePdfsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCombinePdfsData)

	if err != nil {
		return err
	}

	*o = CombinePdfsData(varCombinePdfsData)

	return err
}

type NullableCombinePdfsData struct {
	value *CombinePdfsData
	isSet bool
}

func (v NullableCombinePdfsData) Get() *CombinePdfsData {
	return v.value
}

func (v *NullableCombinePdfsData) Set(val *CombinePdfsData) {
	v.value = val
	v.isSet = true
}

func (v NullableCombinePdfsData) IsSet() bool {
	return v.isSet
}

func (v *NullableCombinePdfsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCombinePdfsData(val *CombinePdfsData) *NullableCombinePdfsData {
	return &NullableCombinePdfsData{value: val, isSet: true}
}

func (v NullableCombinePdfsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCombinePdfsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


