/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuccessMultipleErrorsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuccessMultipleErrorsResponse{}

// SuccessMultipleErrorsResponse struct for SuccessMultipleErrorsResponse
type SuccessMultipleErrorsResponse struct {
	Status string `json:"status"`
	Errors []string `json:"errors,omitempty"`
}

type _SuccessMultipleErrorsResponse SuccessMultipleErrorsResponse

// NewSuccessMultipleErrorsResponse instantiates a new SuccessMultipleErrorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessMultipleErrorsResponse(status string) *SuccessMultipleErrorsResponse {
	this := SuccessMultipleErrorsResponse{}
	this.Status = status
	return &this
}

// NewSuccessMultipleErrorsResponseWithDefaults instantiates a new SuccessMultipleErrorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessMultipleErrorsResponseWithDefaults() *SuccessMultipleErrorsResponse {
	this := SuccessMultipleErrorsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *SuccessMultipleErrorsResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SuccessMultipleErrorsResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SuccessMultipleErrorsResponse) SetStatus(v string) {
	o.Status = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SuccessMultipleErrorsResponse) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessMultipleErrorsResponse) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SuccessMultipleErrorsResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *SuccessMultipleErrorsResponse) SetErrors(v []string) {
	o.Errors = v
}

func (o SuccessMultipleErrorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuccessMultipleErrorsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *SuccessMultipleErrorsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuccessMultipleErrorsResponse := _SuccessMultipleErrorsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuccessMultipleErrorsResponse)

	if err != nil {
		return err
	}

	*o = SuccessMultipleErrorsResponse(varSuccessMultipleErrorsResponse)

	return err
}

type NullableSuccessMultipleErrorsResponse struct {
	value *SuccessMultipleErrorsResponse
	isSet bool
}

func (v NullableSuccessMultipleErrorsResponse) Get() *SuccessMultipleErrorsResponse {
	return v.value
}

func (v *NullableSuccessMultipleErrorsResponse) Set(val *SuccessMultipleErrorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessMultipleErrorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessMultipleErrorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessMultipleErrorsResponse(val *SuccessMultipleErrorsResponse) *NullableSuccessMultipleErrorsResponse {
	return &NullableSuccessMultipleErrorsResponse{value: val, isSet: true}
}

func (v NullableSuccessMultipleErrorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessMultipleErrorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


