/*
DocSpring API

DocSpring provides an API that helps you fill out and sign PDF templates.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package docspring

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateHtmlTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateHtmlTemplate{}

// CreateHtmlTemplate struct for CreateHtmlTemplate
type CreateHtmlTemplate struct {
	Template map[string]interface{} `json:"template"`
}

type _CreateHtmlTemplate CreateHtmlTemplate

// NewCreateHtmlTemplate instantiates a new CreateHtmlTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateHtmlTemplate(template map[string]interface{}) *CreateHtmlTemplate {
	this := CreateHtmlTemplate{}
	this.Template = template
	return &this
}

// NewCreateHtmlTemplateWithDefaults instantiates a new CreateHtmlTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateHtmlTemplateWithDefaults() *CreateHtmlTemplate {
	this := CreateHtmlTemplate{}
	return &this
}

// GetTemplate returns the Template field value
func (o *CreateHtmlTemplate) GetTemplate() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *CreateHtmlTemplate) GetTemplateOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Template, true
}

// SetTemplate sets field value
func (o *CreateHtmlTemplate) SetTemplate(v map[string]interface{}) {
	o.Template = v
}

func (o CreateHtmlTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateHtmlTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["template"] = o.Template
	return toSerialize, nil
}

func (o *CreateHtmlTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"template",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateHtmlTemplate := _CreateHtmlTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateHtmlTemplate)

	if err != nil {
		return err
	}

	*o = CreateHtmlTemplate(varCreateHtmlTemplate)

	return err
}

type NullableCreateHtmlTemplate struct {
	value *CreateHtmlTemplate
	isSet bool
}

func (v NullableCreateHtmlTemplate) Get() *CreateHtmlTemplate {
	return v.value
}

func (v *NullableCreateHtmlTemplate) Set(val *CreateHtmlTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateHtmlTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateHtmlTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateHtmlTemplate(val *CreateHtmlTemplate) *NullableCreateHtmlTemplate {
	return &NullableCreateHtmlTemplate{value: val, isSet: true}
}

func (v NullableCreateHtmlTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateHtmlTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


