/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type SubmissionDataRequest struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Email string `json:"email"`
	Order int32 `json:"order"`
	SortOrder int32 `json:"sort_order"`
	Fields []string `json:"fields"`
	Metadata map[string]interface{} `json:"metadata"`
	State string `json:"state"`
	ViewedAt string `json:"viewed_at,omitempty"`
	CompletedAt string `json:"completed_at,omitempty"`
	AuthType string `json:"auth_type,omitempty"`
	AuthSecondFactorType string `json:"auth_second_factor_type,omitempty"`
	AuthProvider string `json:"auth_provider,omitempty"`
	AuthSessionStartedAt string `json:"auth_session_started_at,omitempty"`
	AuthSessionIdHash string `json:"auth_session_id_hash,omitempty"`
	AuthUserIdHash string `json:"auth_user_id_hash,omitempty"`
	AuthUsernameHash string `json:"auth_username_hash,omitempty"`
	AuthPhoneNumberHash string `json:"auth_phone_number_hash,omitempty"`
	IpAddress string `json:"ip_address,omitempty"`
	UserAgent string `json:"user_agent,omitempty"`
}
