/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type CombinePdfsData struct {
	DeleteCustomFiles bool `json:"delete_custom_files,omitempty"`
	ExpiresIn int32 `json:"expires_in,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Password string `json:"password,omitempty"`
	SourcePdfs []map[string]interface{} `json:"source_pdfs"`
	Test bool `json:"test,omitempty"`
}
