/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package docspring

type TemplatestemplateIdaddFieldsFields struct {
	BackgroundColorFieldName string `json:"backgroundColorFieldName,omitempty"`
	Uppercase bool `json:"uppercase,omitempty"`
	Metadata string `json:"metadata,omitempty"`
	BarcodeSymbology string `json:"barcodeSymbology,omitempty"`
	MinLength float32 `json:"minLength,omitempty"`
	Integer bool `json:"integer,omitempty"`
	Type string `json:"type,omitempty"`
	Required bool `json:"required,omitempty"`
	CombValueOffset float32 `json:"combValueOffset,omitempty"`
	ImageGravity string `json:"imageGravity,omitempty"`
	Overflow string `json:"overflow,omitempty"`
	QrcodeColor string `json:"qrcodeColor,omitempty"`
	ColorFieldRequired bool `json:"colorFieldRequired,omitempty"`
	BackgroundColorFieldRequired bool `json:"backgroundColorFieldRequired,omitempty"`
	Id float32 `json:"id,omitempty"`
	ImageScaleType string `json:"imageScaleType,omitempty"`
	ExclusiveMinimum bool `json:"exclusiveMinimum,omitempty"`
	Height float32 `json:"height,omitempty"`
	NumberConditionRangeExclusiveMax bool `json:"numberConditionRangeExclusiveMax,omitempty"`
	InvertBooleanCondition bool `json:"invertBooleanCondition,omitempty"`
	ShapeFillColorFieldName string `json:"shapeFillColorFieldName,omitempty"`
	Static bool `json:"static,omitempty"`
	ShapeBorderColorFieldName string `json:"shapeBorderColorFieldName,omitempty"`
	VAlignment string `json:"vAlignment,omitempty"`
	Bold bool `json:"bold,omitempty"`
	ShapeBorderWidth float32 `json:"shapeBorderWidth,omitempty"`
	CombNumberOfCells float32 `json:"combNumberOfCells,omitempty"`
	ShapeBorderColor string `json:"shapeBorderColor,omitempty"`
	Comb bool `json:"comb,omitempty"`
	Typeface string `json:"typeface,omitempty"`
	ShapeType string `json:"shapeType,omitempty"`
	Condition string `json:"condition,omitempty"`
	DisplayType string `json:"displayType,omitempty"`
	CheckColor string `json:"checkColor,omitempty"`
	MultilineLines float32 `json:"multilineLines,omitempty"`
	Multiline bool `json:"multiline,omitempty"`
	TrueText string `json:"trueText,omitempty"`
	Name string `json:"name,omitempty"`
	FontSize float32 `json:"fontSize,omitempty"`
	Page float32 `json:"page,omitempty"`
	Alignment string `json:"alignment,omitempty"`
	MaxLength float32 `json:"maxLength,omitempty"`
	AutoCalculateMaxLength bool `json:"autoCalculateMaxLength,omitempty"`
	ColorFieldName string `json:"colorFieldName,omitempty"`
	QrcodeColorFieldName string `json:"qrcodeColorFieldName,omitempty"`
	NumberConditionRangeMin float32 `json:"numberConditionRangeMin,omitempty"`
	Color string `json:"color,omitempty"`
	Hidden bool `json:"hidden,omitempty"`
	CheckColorFieldRequired bool `json:"checkColorFieldRequired,omitempty"`
	CombinedFieldFormat string `json:"combinedFieldFormat,omitempty"`
	Description string `json:"description,omitempty"`
	ShapeBorderColorFieldRequired bool `json:"shapeBorderColorFieldRequired,omitempty"`
	CombinedFieldNames string `json:"combinedFieldNames,omitempty"`
	Title string `json:"title,omitempty"`
	NumberConditionRangeExclusiveMin bool `json:"numberConditionRangeExclusiveMin,omitempty"`
	CombinedFieldSeparator string `json:"combinedFieldSeparator,omitempty"`
	ExclusiveMaximum bool `json:"exclusiveMaximum,omitempty"`
	Default string `json:"default,omitempty"`
	CombinedFieldType string `json:"combinedFieldType,omitempty"`
	DateTimeFormat string `json:"dateTimeFormat,omitempty"`
	QrcodeColorFieldRequired bool `json:"qrcodeColorFieldRequired,omitempty"`
	Currency bool `json:"currency,omitempty"`
	FalseText string `json:"falseText,omitempty"`
	Strikethrough bool `json:"strikethrough,omitempty"`
	CharacterSpacing float32 `json:"characterSpacing,omitempty"`
	NumberConditionRangeMax float32 `json:"numberConditionRangeMax,omitempty"`
	BackgroundColor string `json:"backgroundColor,omitempty"`
	CheckColorFieldName string `json:"checkColorFieldName,omitempty"`
	CheckCharacter string `json:"checkCharacter,omitempty"`
	Rotation float32 `json:"rotation,omitempty"`
	OptionList string `json:"optionList,omitempty"`
	ShapeFillColor string `json:"shapeFillColor,omitempty"`
	StringConditionType string `json:"stringConditionType,omitempty"`
	ShapeFillColorFieldRequired bool `json:"shapeFillColorFieldRequired,omitempty"`
	DecimalPlaces float32 `json:"decimalPlaces,omitempty"`
	IncludeTime bool `json:"includeTime,omitempty"`
	Width float32 `json:"width,omitempty"`
	X float32 `json:"x,omitempty"`
	Maximum float32 `json:"maximum,omitempty"`
	Y float32 `json:"y,omitempty"`
	SignatureAllowDraw bool `json:"signatureAllowDraw,omitempty"`
	NumberConditionType string `json:"numberConditionType,omitempty"`
	Opacity float32 `json:"opacity,omitempty"`
	Minimum float32 `json:"minimum,omitempty"`
	SignatureAllowType bool `json:"signatureAllowType,omitempty"`
}
